### ISSUE TITLE
Deprecated selector in `language-rainmeter\styles\rainmeter.atom-text-editor.less`

### ISSUE THREAD

**Issue by gangadharKorrapati** [NighthawkSLO/language-rainmeter#14]
In `language-rainmeter\styles\rainmeter.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.source.rainmeter .section,
.source.rainmeter .predefined.section` => `.syntax--source.syntax--rainmeter .syntax--section,
.syntax--source.syntax--rainmeter .syntax--predefined.syntax--section`

* `.source.rainmeter .predefined.section` => `.syntax--source.syntax--rainmeter .syntax--predefined.syntax--section`

* `.source.rainmeter .variable,
.source.rainmeter .predefined.variable` => `.syntax--source.syntax--rainmeter .syntax--variable,
.syntax--source.syntax--rainmeter .syntax--predefined.syntax--variable`

* `.source.rainmeter .predefined.variable` => `.syntax--source.syntax--rainmeter .syntax--predefined.syntax--variable`

* `.source.rainmeter .section.variable` => `.syntax--source.syntax--rainmeter .syntax--section.syntax--variable`

* `.source.rainmeter .section.variable.arg` => `.syntax--source.syntax--rainmeter .syntax--section.syntax--variable.arg`

* `.source.rainmeter .invalid` => `.syntax--source.syntax--rainmeter .syntax--invalid`

* `.source.rainmeter .support.function` => `.syntax--source.syntax--rainmeter .syntax--support.syntax--function`

* `.source.rainmeter .support.function.constant` => `.syntax--source.syntax--rainmeter .syntax--support.syntax--function.syntax--constant`

* `.source.rainmeter .deprecated.function` => `.syntax--source.syntax--rainmeter .syntax--deprecated.syntax--function`

* `.source.rainmeter .option` => `.syntax--source.syntax--rainmeter .syntax--option`

* `.source.rainmeter .meter.style.option` => `.syntax--source.syntax--rainmeter .meter.syntax--style.syntax--option`

* `.source.rainmeter .include` => `.syntax--source.syntax--rainmeter .syntax--include`

* `.source.rainmeter .value.constant` => `.syntax--source.syntax--rainmeter .syntax--value.syntax--constant`

* `.source.rainmeter .value.constant.important` => `.syntax--source.syntax--rainmeter .syntax--value.syntax--constant.syntax--important`

* `.source.rainmeter .color.r` => `.syntax--source.syntax--rainmeter .syntax--color.syntax--r`

* `.source.rainmeter .color.g` => `.syntax--source.syntax--rainmeter .syntax--color.syntax--g`

* `.source.rainmeter .color.b` => `.syntax--source.syntax--rainmeter .syntax--color.syntax--b`

* `.source.rainmeter .color.a` => `.syntax--source.syntax--rainmeter .syntax--color.syntax--a`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by marcopixel** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by marcopixel** [comment]
Fixed with #16, thanks for your support.
