### ISSUE TITLE
Add continuous integration and code testing

### ISSUE THREAD

**Issue by marcopixel** [NighthawkSLO/language-rainmeter#20]
### Prerequisites

* [x] You are using the most recent release of **language-rainmeter**
* [x] You have checked that your issue hasn't already been addressed by an [existing issue](https://github.com/MarcoPixel/language-rainmeter/issues?utf8=%E2%9C%93&q=is%3Aissue)

### Description

We should add continuous integration and automatic code integration to properly check if pull requests can be merged without issues and also to check if some of our commits break the package. 

CI is no big deal as there is a example from Atom itself and it worked just fine, but the big problem is the spec as it seems that it won't detect the scopes of the general options (it will just find the source.rainmeter scope on the example string ```Meter=Image```)

I will commit my current state on a new branch called [add-ci-code-testing](https://github.com/MarcoPixel/language-rainmeter/tree/add-ci-code-testing) later and maybe someone can figure out why the hell this isnt working.

### Additional Information

Guide to include CI to Atom packages: https://github.com/atom/ci
Writing specs (Guide to create automatic tests): https://flight-manual.atom.io/hacking-atom/sections/writing-specs/
Example spec file: https://github.com/atom/language-xml/blob/master/spec/xml-spec.coffee

**Comment by tterb** [comment]
Although I haven't set up CI for an Atom package, I have a little experience using Travis CI in another project so I'll take a look and see if I can figure out what the issue is.

**Comment by tterb** [comment]
After experimenting with it, I think I'm running into the same issue with the spec where `grammar.tokenizeLine('Meter=Image')` isn't properly tokenizing the string. 
I'll look at the specs of some of the core languages and see how they approach similar syntax.

**Comment by marcopixel** [comment]
Sounds good :)

I'll try to get some stuff working in the next few days but i'm quite busy right now so i might not get that much done.
