### ISSUE TITLE
Issue with 'MouseActionCursor' scope

### ISSUE THREAD

**Issue by tterb** [NighthawkSLO/language-rainmeter#21]
### Prerequisites

* [x] You are using the most recent release of **language-rainmeter**
* [x] You have checked that your issue hasn't already been addressed by an [existing issue](https://github.com/MarcoPixel/language-rainmeter/issues?utf8=%E2%9C%93&q=is%3Aissue)

### Description

The [MouseActionCursor](https://docs.rainmeter.net/manual/mouse-actions/#MouseActionCursor) option isn't being recognized as a 1/0 option. 

### Steps to Reproduce

1. Open a skin file that contains the `MouseActionCursor` option

**Expected behavior:** [What you expect to happen]
The options 1/0 value should be within the `value.constant.rainmeter` scope

**Actual behavior:** [What actually happens]
The only scope of the options 1/0 value is `source.rainmeter`

**Reproduces how often:** [What percentage of the time does it reproduce?]  
100%

**Comment by marcopixel** [comment]
Fixed with 9d5079ffd848f027514075d5ad01fe72cac00cee.
