### ISSUE TITLE
Numbers In Strings Colored As RGBA

### ISSUE THREAD

**Issue by collinjackson93** [NighthawkSLO/language-rainmeter#9]
It seems like RGBA-like values are being colored as such, even though they aren't valid RGBA. See the below screenshot for an example.

![image](https://cloud.githubusercontent.com/assets/5580739/14567127/4997292c-02f8-11e6-96ab-9f3a56fa08a4.png)

**Comment by NighthawkSLO** [comment]
there are a few ways i could go about fixing this, but i think i'll go with having either a `=`, a space or a new line in front and the back of the color code

edit: should probably make it possible for it to be surrounded in quotes

**Comment by NighthawkSLO** [comment]
fixed in ddaff5370c07c3a1fd97665f469a796c36384aa8

**Comment by collinjackson93** [comment]
I just tried it and it seems to work fine. Thanks for the quick response and fix!
